language: node_js
node_js:
  - "8.9.4"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ad1db4304590f2f96eb88b3d0726831454e302f5
  keep-history: true
  local-dir: ./build
  on:
    branch: master
script: yarn build